"""Draft generation helpers for provider-to-provider migrations."""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from replicator.schema import validate_bundle_payload


SUPPORTED_TARGETS = {"codex"}


@dataclass(frozen=True)
class DraftResult:
    artifact_id: str
    source_provider: str
    source_path: str
    target_provider: str
    target_path: str
    status: str
    reason: str


def slugify_skill_name(name: str) -> str:
    lowered = name.strip().lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", lowered)
    slug = re.sub(r"-{2,}", "-", slug).strip("-._")
    return slug or "unnamed-skill"


def load_bundle(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    validate_bundle_payload(payload)
    return payload


def is_claude_skill_entry(artifact: dict[str, Any]) -> bool:
    return (
        artifact.get("provider") == "claude"
        and artifact.get("artifact_type") == "skill_or_prompt"
        and artifact.get("classification") == "portable_with_edits"
        and artifact.get("contains_secret_reference") is False
        and str(artifact.get("path", "")).replace("\\", "/").endswith("/SKILL.md")
    )


def migration_notes(artifact: dict[str, Any], target_path: Path) -> str:
    checksum = artifact.get("checksum_sha256") or "not available"
    checksum_status = artifact.get("checksum_status") or "unknown"
    return "\n".join(
        [
            "# Migration Notes",
            "",
            "This is a draft generated by Replicator. Review it before installing it into a live provider config.",
            "",
            "## Source",
            "",
            f"- Source provider: `{artifact.get('provider')}`",
            f"- Source path: `{artifact.get('path')}`",
            f"- Artifact ID: `{artifact.get('artifact_id')}`",
            f"- Artifact type: `{artifact.get('artifact_type')}`",
            f"- Classification: `{artifact.get('classification')}`",
            f"- Checksum status: `{checksum_status}`",
            f"- SHA-256: `{checksum}`",
            "",
            "## Target",
            "",
            "- Target provider: `codex`",
            f"- Draft path: `{target_path}`",
            "",
            "## Safety",
            "",
            "- Credentials, session files, OAuth tokens, and API keys were not copied.",
            "- Discovered scripts, hooks, and dependencies were not executed.",
            "- Provider-specific behavior may need manual adaptation.",
            "",
            "## Manual Review Checklist",
            "",
            "- Confirm the instructions make sense for Codex.",
            "- Remove references to Claude-only commands or assumptions.",
            "- Recreate any required credentials manually in the receiving provider.",
            "- Test the draft in an isolated Codex session before installing it globally.",
            "",
        ]
    )


def generate_codex_drafts(bundle_path: Path, output_dir: Path) -> list[DraftResult]:
    payload = load_bundle(bundle_path)
    draft_root = output_dir / "codex" / "skills"
    draft_root.mkdir(parents=True, exist_ok=True)

    results: list[DraftResult] = []
    for artifact in payload["artifacts"]:
        source_path = Path(str(artifact.get("path", "")))
        if not is_claude_skill_entry(artifact):
            results.append(
                DraftResult(
                    artifact_id=str(artifact.get("artifact_id", "")),
                    source_provider=str(artifact.get("provider", "")),
                    source_path=str(artifact.get("path", "")),
                    target_provider="codex",
                    target_path="",
                    status="skipped",
                    reason="Only portable Claude SKILL.md artifacts are generated in v0.5.0.",
                )
            )
            continue

        if not source_path.is_file():
            results.append(
                DraftResult(
                    artifact_id=str(artifact.get("artifact_id", "")),
                    source_provider="claude",
                    source_path=str(source_path),
                    target_provider="codex",
                    target_path="",
                    status="skipped",
                    reason="Source SKILL.md file is not readable from this machine.",
                )
            )
            continue

        skill_name = slugify_skill_name(source_path.parent.name)
        target_skill_dir = draft_root / skill_name
        target_skill_dir.mkdir(parents=True, exist_ok=True)
        target_skill_path = target_skill_dir / "SKILL.md"
        target_notes_path = target_skill_dir / "MIGRATION_NOTES.md"

        shutil.copyfile(source_path, target_skill_path)
        target_notes_path.write_text(migration_notes(artifact, target_skill_path), encoding="utf-8")
        results.append(
            DraftResult(
                artifact_id=str(artifact.get("artifact_id", "")),
                source_provider="claude",
                source_path=str(source_path),
                target_provider="codex",
                target_path=str(target_skill_path),
                status="generated",
                reason="Generated Codex skill draft from Claude SKILL.md.",
            )
        )

    manifest_path = output_dir / "codex" / "manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "target_provider": "codex",
        "source_bundle": str(bundle_path),
        "generated_count": sum(1 for result in results if result.status == "generated"),
        "skipped_count": sum(1 for result in results if result.status == "skipped"),
        "results": [asdict(result) for result in results],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return results

