"""Draft generation helpers for provider-to-provider migrations."""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from replicator.schema import validate_bundle_payload


SUPPORTED_SOURCES = {"claude", "codex", "kimi", "openclaw", "qwen"}
SUPPORTED_TARGETS = {"claude", "codex"}


@dataclass(frozen=True)
class DraftResult:
    artifact_id: str
    source_provider: str
    source_path: str
    target_provider: str
    target_path: str
    status: str
    reason: str


def slugify_skill_name(name: str) -> str:
    lowered = name.strip().lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", lowered)
    slug = re.sub(r"-{2,}", "-", slug).strip("-._")
    return slug or "unnamed-skill"


def load_bundle(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    validate_bundle_payload(payload)
    return payload


def is_portable_prompt_entry(artifact: dict[str, Any], source_provider: str) -> bool:
    path = str(artifact.get("path", "")).replace("\\", "/")
    return (
        artifact.get("provider") == source_provider
        and artifact.get("artifact_type") == "skill_or_prompt"
        and artifact.get("classification") == "portable_with_edits"
        and artifact.get("contains_secret_reference") is False
        and Path(path).suffix.lower() in {".md", ".txt"}
    )


def is_portable_mcp_entry(artifact: dict[str, Any], source_provider: str) -> bool:
    path = str(artifact.get("path", "")).replace("\\", "/")
    return (
        artifact.get("provider") == source_provider
        and artifact.get("artifact_type") == "mcp_config"
        and artifact.get("classification") == "portable_with_edits"
        and artifact.get("contains_secret_reference") is False
        and Path(path).suffix.lower() in {".json", ".toml", ".yaml", ".yml"}
    )


def is_skill_file(path: Path) -> bool:
    return path.name == "SKILL.md"


def target_skill_name(source_path: Path) -> str:
    if is_skill_file(source_path):
        return slugify_skill_name(source_path.parent.name)
    return slugify_skill_name(source_path.stem)


def converted_prompt_content(artifact: dict[str, Any], source_path: Path) -> str:
    source_text = source_path.read_text(encoding="utf-8")
    title = source_path.stem.replace("_", " ").replace("-", " ").strip().title() or "Migrated Instructions"
    return "\n".join(
        [
            f"# {title}",
            "",
            "This draft was converted by Replicator from a source-provider command, prompt, or agent markdown file.",
            "",
            "Review provider-specific assumptions before installing it into live config.",
            "",
            "## Source",
            "",
            f"- Provider: `{artifact.get('provider')}`",
            f"- Path: `{artifact.get('path')}`",
            f"- Artifact ID: `{artifact.get('artifact_id')}`",
            "",
            "## Instructions",
            "",
            source_text,
            "",
        ]
    )


def migration_notes(artifact: dict[str, Any], target_provider: str, target_path: Path) -> str:
    checksum = artifact.get("checksum_sha256") or "not available"
    checksum_status = artifact.get("checksum_status") or "unknown"
    return "\n".join(
        [
            "# Migration Notes",
            "",
            "This is a draft generated by Replicator. Review it before installing it into a live provider config.",
            "",
            "## Source",
            "",
            f"- Source provider: `{artifact.get('provider')}`",
            f"- Source path: `{artifact.get('path')}`",
            f"- Artifact ID: `{artifact.get('artifact_id')}`",
            f"- Artifact type: `{artifact.get('artifact_type')}`",
            f"- Classification: `{artifact.get('classification')}`",
            f"- Checksum status: `{checksum_status}`",
            f"- SHA-256: `{checksum}`",
            "",
            "## Target",
            "",
            f"- Target provider: `{target_provider}`",
            f"- Draft path: `{target_path}`",
            "",
            "## Safety",
            "",
            "- Credentials, session files, OAuth tokens, and API keys were not copied.",
            "- Discovered scripts, hooks, and dependencies were not executed.",
            "- Provider-specific behavior may need manual adaptation.",
            "",
            "## Manual Review Checklist",
            "",
            f"- Confirm the instructions make sense for {target_provider}.",
            "- Remove references to source-provider-only commands or assumptions.",
            "- Recreate any required credentials manually in the receiving provider.",
            f"- Test the draft in an isolated {target_provider} session before installing it globally.",
            "",
        ]
    )


def target_mcp_name(source_path: Path) -> str:
    return f"{slugify_skill_name(source_path.stem)}{source_path.suffix.lower()}"


def mcp_migration_notes(artifact: dict[str, Any], target_provider: str, target_path: Path) -> str:
    checksum = artifact.get("checksum_sha256") or "not available"
    checksum_status = artifact.get("checksum_status") or "unknown"
    return "\n".join(
        [
            "# MCP Migration Notes",
            "",
            "This MCP config draft was copied by Replicator for manual review.",
            "",
            "Replicator does not execute MCP commands, install servers, validate executable paths, or copy credentials.",
            "",
            "## Source",
            "",
            f"- Source provider: `{artifact.get('provider')}`",
            f"- Source path: `{artifact.get('path')}`",
            f"- Artifact ID: `{artifact.get('artifact_id')}`",
            f"- Checksum status: `{checksum_status}`",
            f"- SHA-256: `{checksum}`",
            "",
            "## Target",
            "",
            f"- Target provider: `{target_provider}`",
            f"- Draft path: `{target_path}`",
            "",
            "## Manual Review Checklist",
            "",
            "- Verify command paths exist on this machine.",
            "- Recreate required environment variables and credentials manually.",
            "- Confirm the receiving provider supports the same MCP shape.",
            "- Test the server in an isolated session before installing it globally.",
            "",
        ]
    )


def generate_skill_drafts(
    bundle_path: Path,
    output_dir: Path,
    *,
    source_provider: str,
    target_provider: str,
) -> list[DraftResult]:
    if source_provider not in SUPPORTED_SOURCES:
        raise ValueError(f"unsupported source provider: {source_provider}")
    if target_provider not in SUPPORTED_TARGETS:
        raise ValueError(f"unsupported target provider: {target_provider}")

    payload = load_bundle(bundle_path)
    skill_draft_root = output_dir / target_provider / "skills"
    mcp_draft_root = output_dir / target_provider / "mcp"
    skill_draft_root.mkdir(parents=True, exist_ok=True)
    mcp_draft_root.mkdir(parents=True, exist_ok=True)

    results: list[DraftResult] = []
    for artifact in payload["artifacts"]:
        source_path = Path(str(artifact.get("path", "")))
        if is_portable_prompt_entry(artifact, source_provider):
            if not source_path.is_file():
                results.append(
                    DraftResult(
                        artifact_id=str(artifact.get("artifact_id", "")),
                        source_provider=source_provider,
                        source_path=str(source_path),
                        target_provider=target_provider,
                        target_path="",
                        status="skipped",
                        reason="Source skill/prompt file is not readable from this machine.",
                    )
                )
                continue

            skill_name = target_skill_name(source_path)
            target_skill_dir = skill_draft_root / skill_name
            target_skill_dir.mkdir(parents=True, exist_ok=True)
            target_skill_path = target_skill_dir / "SKILL.md"
            target_notes_path = target_skill_dir / "MIGRATION_NOTES.md"

            if is_skill_file(source_path):
                shutil.copyfile(source_path, target_skill_path)
            else:
                target_skill_path.write_text(converted_prompt_content(artifact, source_path), encoding="utf-8")
            target_notes_path.write_text(migration_notes(artifact, target_provider, target_skill_path), encoding="utf-8")
            results.append(
                DraftResult(
                    artifact_id=str(artifact.get("artifact_id", "")),
                    source_provider=source_provider,
                    source_path=str(source_path),
                    target_provider=target_provider,
                    target_path=str(target_skill_path),
                    status="generated",
                    reason=f"Generated {target_provider} skill draft from {source_provider} skill/prompt artifact.",
                )
            )
            continue

        if is_portable_mcp_entry(artifact, source_provider):
            if not source_path.is_file():
                results.append(
                    DraftResult(
                        artifact_id=str(artifact.get("artifact_id", "")),
                        source_provider=source_provider,
                        source_path=str(source_path),
                        target_provider=target_provider,
                        target_path="",
                        status="skipped",
                        reason="Source MCP config file is not readable from this machine.",
                    )
                )
                continue

            target_mcp_dir = mcp_draft_root / slugify_skill_name(source_path.stem)
            target_mcp_dir.mkdir(parents=True, exist_ok=True)
            target_mcp_path = target_mcp_dir / target_mcp_name(source_path)
            target_notes_path = target_mcp_dir / "MIGRATION_NOTES.md"
            shutil.copyfile(source_path, target_mcp_path)
            target_notes_path.write_text(mcp_migration_notes(artifact, target_provider, target_mcp_path), encoding="utf-8")
            results.append(
                DraftResult(
                    artifact_id=str(artifact.get("artifact_id", "")),
                    source_provider=source_provider,
                    source_path=str(source_path),
                    target_provider=target_provider,
                    target_path=str(target_mcp_path),
                    status="generated",
                    reason=f"Generated {target_provider} MCP draft from {source_provider} MCP config.",
                )
            )
            continue

        results.append(
            DraftResult(
                artifact_id=str(artifact.get("artifact_id", "")),
                source_provider=str(artifact.get("provider", "")),
                source_path=str(artifact.get("path", "")),
                target_provider=target_provider,
                target_path="",
                status="skipped",
                reason=f"Only portable {source_provider} skill/prompt and MCP artifacts are generated for {target_provider}.",
            )
        )

    manifest_path = output_dir / target_provider / "manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "source_provider": source_provider,
        "target_provider": target_provider,
        "source_bundle": str(bundle_path),
        "generated_count": sum(1 for result in results if result.status == "generated"),
        "skipped_count": sum(1 for result in results if result.status == "skipped"),
        "results": [asdict(result) for result in results],
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return results


def generate_codex_drafts(
    bundle_path: Path,
    output_dir: Path,
    *,
    source_provider: str = "claude",
) -> list[DraftResult]:
    return generate_skill_drafts(
        bundle_path,
        output_dir,
        source_provider=source_provider,
        target_provider="codex",
    )


def generate_claude_drafts(
    bundle_path: Path,
    output_dir: Path,
    *,
    source_provider: str = "codex",
) -> list[DraftResult]:
    return generate_skill_drafts(
        bundle_path,
        output_dir,
        source_provider=source_provider,
        target_provider="claude",
    )
